[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
 
[project]
name = "fossilfree-ecoinvent"  # name on PyPI (can differ from module name)
version = "0.1.6"
description = "Tools to generate fossil-free ecoinvent-based LCI databases"
readme = "README.md"
requires-python = ">=3.9,<3.13"
 
authors = [
  { name = "Hauke Schlesier"        , email = "hauke.schlesier@empa.ch" },
  { name = "Carlos Gomez-Camacho"   , email = "carlos.gomez@empa.ch" }
]
 
license = { text = "MIT" }

dependencies = [
  "numpy==1.26.4",
  "pandas==2.2.3",
  "bw2data==3.6.6",
  "bw2io==0.8.12",
  "bw2calc==1.8.2",
  "pyecospold==3.5.3",
  "stats_arrays==0.7",
  "carculator==1.7.1",
  "carculator-truck==0.3.6",
  "carculator-utils==1.3.4",
  "openpyxl==3.1.5",
  "tqdm==4.67.1",
  "lxml>=4.9.3"
]
 
[project.urls]
Homepage = "https://github.com/hschlesier/fossilfree_ecoinvent"
Repository = "https://github.com/hschlesier/fossilfree_ecoinvent"
 
#[project.scripts]
#fossilfree-ecoinvent = "fossilfree_ecoinvent.cli:main"
 
# -----------------------------
# Setuptools configuration
# -----------------------------
[tool.setuptools]
package-dir = {"" = "src"}
license-files = ["LICENSE"] 
 
[tool.setuptools.packages.find]
where = ["src"]
include = ["fossilfree_ecoinvent*"]
 
[tool.setuptools.package-data]
fossilfree_ecoinvent = ["data/**"]